package generator

import (
	"fmt"
	"strings"

	. "github.com/dave/jennifer/jen"

	"github.com/iancoleman/strcase"

	"github.com/arisu-archive/bluearchive-fbs-generator/parser"
)

// generateModel creates Go struct definitions that match FlatBuffers schema.
func generateModel(s *parser.Schema, pkgName, outputDir string) error {
	f := NewFile(pkgName)

	// Add package documentation
	f.PackageComment("Code generated by fbsgen. DO NOT EDIT.")
	f.PackageComment(fmt.Sprintf("Package %s contains generated code for FlatBuffers schema", pkgName))

	// Generate a struct for each definition
	written := false
	for _, def := range s.Definitions {
		switch def.Type {
		case parser.TypeStruct, parser.TypeTable:
			generateStructType(f, def)
			generateStructMarshaler(f, def)
			generateStructUnmarshaler(f, def)
			written = true
		case parser.TypeUnion:
			generateUnionType(f, def)
			written = true
		case parser.TypeEnum:
			continue
		}
	}

	if written {
		// Save the generated code
		return writeFile(f, outputDir, fmt.Sprintf("%s.go", toExportedName(s.FileName)))
	}

	return nil
}

// generateStructType creates a Go struct for a FlatBuffers struct or table.
func generateStructType(f *File, def parser.Definition) {
	modelName := toExportedName(def.Name)
	// Add documentation for the struct
	f.Comment(fmt.Sprintf("%s represents a FlatBuffers %s", modelName, getDefTypeStr(def.Type)))
	// Import the flatbuffers package
	f.ImportAlias("github.com/google/flatbuffers/go", "flatbuffers")
	f.ImportAlias("github.com/arisu-archive/bluearchive-fbs-utils", "fbsutils")
	f.ImportName("errors", "errors")
	// Begin struct definition
	structDef := Type().Id(modelName)

	// Add fields to the struct
	fields := []Code{
		Qual("github.com/arisu-archive/bluearchive-fbs-utils", "FlatBuffer"),
	}
	for _, field := range def.Fields {
		// Generate field with appropriate type
		fieldType := getGoType(field)
		fields = append(fields, Id(toExportedName(field.Name)).Add(fieldType).Tag(map[string]string{
			"json": field.Name,
		}))
	}

	// Add the struct to the file
	f.Add(structDef.Struct(fields...))
	f.Line()
}

func generateStructUnmarshaler(f *File, def parser.Definition) {
	modelName := toExportedName(def.Name)
	f.Comment("Unmarshal unmarshals the struct from a FlatBuffers buffer")
	f.Func().Params(Id("t").Op("*").Id(modelName)).Id("Unmarshal").Params(
		Id("data").Index().Add(Byte()),
	).Params(
		Error(),
	).BlockFunc(func(g *Group) {
		g.Id("err").Op(":=").Id("t").Dot("UnmarshalMessage").Call(Id("GetRootAs"+def.Name).Call(Id("data"), Lit(0)))
		// If err != nil, return err
		g.If(Id("err").Op("!=").Nil()).Block(
			Return(Id("err")),
		)
		g.Return(Nil())
	})

	f.Line()

	f.Comment("UnmarshalMessage unmarshals the struct from a FlatBuffers buffer")
	f.Func().Params(Id("t").Op("*").Id(modelName)).Id("UnmarshalMessage").Params(
		Id("e").Op("*").Id(strcase.ToCamel(def.Name)),
	).Params(
		Error(),
	).BlockFunc(func(g *Group) {
		for _, field := range def.Fields {
			assign := g.Id("t").Dot(toExportedName(field.Name)).Op("=")
			// TODO: Use more generic method to handle struct references
			if strings.Contains(field.Name, "data_list") {
				assign.Make(Id("[]"+toExportedName(field.Type)), Id("e").Dot(toExportedName(field.Name)+"Length").Call())
				g.For(Id("i").Op(":=").Range().Id("e").Dot(toExportedName(field.Name) + "Length").Call()).BlockFunc(func(g *Group) {
					g.Id("d").Op(":=").New(Id(strcase.ToCamel(field.Type)))
					g.If(Op("!").Id("e").Dot(toExportedName(field.Name)).Call(Id("d"), Id("i"))).Block(
						Return(Qual("errors", "New").Call(Lit("failed to unmarshal data"))),
					)
					g.Id("t").Dot(toExportedName(field.Name)).Index(Id("i")).Dot("UnmarshalMessage").Call(Id("d"))
				})
			} else if field.IsVector {
				assign.Make(getGoType(field), Id("e").Dot(toExportedName(field.Name)+"Length").Call())
				g.For(Id("i").Op(":=").Range().Id("e").Dot(toExportedName(field.Name) + "Length").Call()).BlockFunc(func(g *Group) {
					isPrimitive := field.IsPrimitive()
					// If the field is not a primitive type, we need to wrap it in an Int32
					fieldAccessor := Id("e").Dot(toExportedName(field.Name)).Call(Id("i"))
					convertFunc := func(field Code) Code {
						return Qual("github.com/arisu-archive/bluearchive-fbs-utils", "Convert").Call(
							field,
							Id("t").Dot("FlatBuffer").Dot("TableKey"),
						)
					}
					convertCall := convertFunc(fieldAccessor)
					if !isPrimitive {
						fieldAccessor = Id("int32").Call(fieldAccessor)
						convertCall = Id(toExportedName(field.Type)).Call(convertFunc(fieldAccessor))
					}
					g.Id("t").Dot(toExportedName(field.Name)).Index(Id("i")).Op("=").Add(convertCall)
				})
			} else {
				convertFunc := func(field Code) Code {
					return Qual("github.com/arisu-archive/bluearchive-fbs-utils", "Convert").Call(field, Id("t").Dot("FlatBuffer").Dot("TableKey"))
				}
				fieldAccessor := Id("e").Dot(toExportedName(field.Name)).Call()
				convertCall := convertFunc(fieldAccessor)
				if field.IsString {
					convertCall = convertFunc(Id("string").Call(fieldAccessor))
				} else if !field.IsPrimitive() {
					// It is enum type
					convertCall = Id(toExportedName(field.Type)).Call(convertFunc(Id("int32").Call(fieldAccessor)))
				}
				assign.Add(convertCall)
			}
		}
		g.Return(Nil())
	})

	f.Line()
}

// generateStructMarshaler creates a Go marshaler for a FlatBuffers struct.
func generateStructMarshaler(f *File, def parser.Definition) {
	// Add documentation for the Marshal method
	convertFunc := func(field Code) Code {
		return Qual("github.com/arisu-archive/bluearchive-fbs-utils", "Convert").Call(field, Id("t").Dot("FlatBuffer").Dot("TableKey"))
	}
	modelName := toExportedName(def.Name)
	f.Comment("MarshalModel marshals the struct into flatbuffers offset")
	f.Func().Params(Id("t").Op("*").Id(modelName)).Id("MarshalModel").Params(
		Id("b").Op("*").Qual("github.com/google/flatbuffers/go", "Builder"),
	).Qual("github.com/google/flatbuffers/go", "UOffsetT").BlockFunc(func(g *Group) {
		g.Id(def.Name + "Start").Call(Id("b"))
		for _, field := range def.Fields {
			// Check if the field is a primitive type
			fieldAccessor := Id("t").Dot(toExportedName(field.Name))
			if field.IsVector {
				g.Id(def.Name+"Start"+toExportedName(field.Name)+"Vector").Call(Id("b"), Id("len").Call(
					fieldAccessor,
				))
				g.For(Id("i").Op(":=").Id("len").Call(fieldAccessor).Op("-").Lit(1), Id("i").Op(">=").Lit(0), Id("i").Op("--")).BlockFunc(func(g *Group) {
					// TODO: Use a more generic way to handle struct references
					if strings.Contains(field.Name, "data_list") {
						g.Id("b").Dot("PrependUOffsetT").Call(Id("t").Dot(toExportedName(field.Name)).Index(Id("i")).Dot("MarshalModel").Call(Id("b")))
					} else {
						isPrimitive := field.IsPrimitive()
						goType := getBaseGoType(field).GoString()
						// If the field is not a primitive type, we need to wrap it in an Int32
						fieldAccessorWrapper := fieldAccessor.Clone().Index(Id("i"))
						if !isPrimitive {
							goType = "Int32"
							fieldAccessorWrapper = Id("int32").Call(fieldAccessorWrapper)
						} else if field.IsString {
							goType = "UOffsetT"
							fieldAccessorWrapper = Id("b").Dot("CreateString").Call(fieldAccessorWrapper)
						}
						// b.PrependXXX(fbsutils.Convert(t.FieldName))
						g.Id("b").Dot("Prepend" + strcase.ToCamel(goType)).Call(convertFunc(fieldAccessorWrapper))
					}
				})
				g.Id(def.Name+"Add"+toExportedName(field.Name)).Call(
					Id("b"),
					Id("b").Dot("EndVector").Call(Id("len").Call(fieldAccessor)),
				)
			} else if !field.IsVector && (field.IsPrimitive() || !strings.Contains(field.Name, "Excel")) {
				// TODO: Use a more generic way to handle struct references
				if field.IsString {
					fieldAccessor = Id("b").Dot("CreateString").Call(fieldAccessor)
				}
				g.Id(def.Name+"Add"+toExportedName(field.Name)).Call(
					Id("b"),
					convertFunc(fieldAccessor),
				)
			} else {
				panic("unknown field type: " + field.Type)
			}
		}
		g.Return(Id(def.Name + "End").Call(Id("b")))
	})

	f.Line()

	f.Comment("Marshal marshals the struct into a FlatBuffers buffer")
	f.Func().Params(Id("t").Op("*").Id(modelName)).Id("Marshal").Params().Params(
		Index().Add(Byte()),
		Error(),
	).BlockFunc(func(g *Group) {
		g.Id("b").Op(":=").Qual("github.com/google/flatbuffers/go", "NewBuilder").Call(Lit(0))
		g.Id("Finish"+def.Name+"Buffer").Call(
			Id("b"),
			Id("t").Dot("MarshalModel").Call(Id("b")),
		)
		g.Return(
			Id("b").Dot("FinishedBytes").Call(),
			Nil(),
		)
	})
	f.Line()
}

// generateUnionType creates a Go type for a FlatBuffers union
func generateUnionType(f *File, def parser.Definition) {
	// Add documentation for the union
	f.Comment(fmt.Sprintf("%s represents a FlatBuffers union", def.Name))

	// For unions, we'll create an interface
	f.Type().Id(def.Name).Interface(
		Id("is" + def.Name).Params().Op("()"),
	)
	f.Line()

	// Also generate a type discriminator enum
	f.Comment(fmt.Sprintf("%sType represents the type of %s union", def.Name, def.Name))
	f.Type().Id(def.Name + "Type").Byte()
	f.Line()

	// Each union value gets a constant
	f.Const().DefsFunc(func(g *Group) {
		g.Id(def.Name + "TypeNONE").Op("=").Lit(0)
		for i, field := range def.Fields {
			g.Id(def.Name + "Type" + toExportedName(field.Name)).Op("=").Lit(i + 1)
		}
	})
	f.Line()
}
