package generator

import (
	"fmt"

	"github.com/dave/jennifer/jen"

	"github.com/arisu-archive/bluearchive-fbs-generator/parser"
)

// buildModelFile creates Go struct definitions that match a FlatBuffers schema.
func buildModelFile(s *parser.Schema, packageName string, withoutDecryption bool) (*jen.File, string, bool) {
	file := jen.NewFile(packageName)
	file.PackageComment("Code generated by fbsgen. DO NOT EDIT.")
	file.PackageComment(fmt.Sprintf("Package %s contains generated code for a FlatBuffers schema.", packageName))

	written := false
	for _, definition := range s.Definitions {
		switch definition.Type {
		case parser.TypeTable:
			generateTableType(file, definition)
			generateTableMarshaler(file, definition, withoutDecryption)
			generateTableUnmarshaler(file, definition, withoutDecryption)
			generateTableName(file, definition)
			written = true
		case parser.TypeStruct, parser.TypeUnion, parser.TypeEnum:
			continue
		}
	}
	if !written {
		return file, "", false
	}
	return file, toFileName(s.FileName), true
}

func generateTableType(file *jen.File, definition parser.Definition) {
	modelName := toModelName(definition.Name)
	file.Comment(fmt.Sprintf("%s represents a FlatBuffers table.", modelName))
	file.ImportAlias("github.com/google/flatbuffers/go", "flatbuffers")
	file.ImportAlias("github.com/arisu-archive/bluearchive-fbs-utils", "fbsutils")

	fields := make([]jen.Code, 0, len(definition.Fields)+1)
	fields = append(fields, jen.Qual("github.com/arisu-archive/bluearchive-fbs-utils", "FlatBuffer"))
	for _, field := range definition.Fields {
		fields = append(fields, jen.Id(toExportedName(field.Name)).Add(getGoType(field)).Tag(map[string]string{
			"json": field.Name,
		}))
	}

	file.Type().Id(modelName).Struct(fields...)
	file.Line()
}

func generateTableName(file *jen.File, definition parser.Definition) {
	modelName := toModelName(definition.Name)
	file.Comment("FlatDataName returns the FlatBuffers table name.")
	file.Func().Params(jen.Id(modelName)).Id("FlatDataName").Params().String().Block(
		jen.Return(jen.Lit(definition.Name)),
	)
	file.Line()
}
