package generator

import (
	"fmt"

	. "github.com/dave/jennifer/jen"

	"github.com/arisu-archive/bluearchive-fbs-generator/parser"
)

// generateModel creates Go struct definitions that match FlatBuffers schema.
func generateModel(s *parser.Schema, pkgName, outputDir string) error {
	f := NewFile(pkgName)

	// Add package documentation
	f.PackageComment("Code generated by fbsgen. DO NOT EDIT.")
	f.PackageComment(fmt.Sprintf("Package %s contains generated code for FlatBuffers schema", pkgName))

	// Generate a struct for each definition
	written := false
	for _, def := range s.Definitions {
		switch def.Type {
		case parser.TypeStruct, parser.TypeTable:
			generateStructType(f, def)
			generateStructMarshaler(f, def)
			generateStructUnmarshaler(f, def)
			generateStructName(f, def)
			written = true
		case parser.TypeUnion:
			generateUnionType(f, def)
			written = true
		case parser.TypeEnum:
			continue
		}
	}

	if written {
		// Save the generated code
		return writeFile(f, outputDir, fmt.Sprintf("%s.go", toModelName(s.FileName)))
	}

	return nil
}

// generateStructType creates a Go struct for a FlatBuffers struct or table.
func generateStructType(f *File, def parser.Definition) {
	modelName := toModelName(def.Name)
	// Add documentation for the struct
	f.Comment(fmt.Sprintf("%s represents a FlatBuffers %s", modelName, getDefTypeStr(def.Type)))
	// Import the flatbuffers package
	f.ImportAlias("github.com/google/flatbuffers/go", "flatbuffers")
	f.ImportAlias("github.com/arisu-archive/bluearchive-fbs-utils", "fbsutils")
	f.ImportName("errors", "errors")
	// Begin struct definition
	structDef := Type().Id(modelName)

	// Add fields to the struct
	fields := []Code{
		Qual("github.com/arisu-archive/bluearchive-fbs-utils", "FlatBuffer"),
	}
	for _, field := range def.Fields {
		// Generate field with appropriate type
		fieldType := getGoType(field)
		fields = append(fields, Id(toExportedName(field.Name)).Add(fieldType).Tag(map[string]string{
			"json": field.Name,
		}))
	}

	// Add the struct to the file
	f.Add(structDef.Struct(fields...))
	f.Line()
}

// generateStructName generates a method that returns the name of the struct.
func generateStructName(f *File, def parser.Definition) {
	modelName := toModelName(def.Name)
	f.Comment("Name returns the name of the flatbuffer table name")
	f.Func().Params(Id(modelName)).Id("FlatDataName").Params().String().BlockFunc(func(g *Group) {
		g.Return(Lit(def.Name))
	})
	f.Line()
}

// generateUnionType creates a Go type for a FlatBuffers union.
func generateUnionType(f *File, def parser.Definition) {
	// Add documentation for the union
	f.Comment(fmt.Sprintf("%s represents a FlatBuffers union", def.Name))

	// For unions, we'll create an interface
	f.Type().Id(def.Name).Interface(
		Id("is" + def.Name).Params().Op("()"),
	)
	f.Line()

	// Also generate a type discriminator enum
	f.Comment(fmt.Sprintf("%sType represents the type of %s union", def.Name, def.Name))
	f.Type().Id(def.Name + "Type").Byte()
	f.Line()

	// Each union value gets a constant
	f.Const().DefsFunc(func(g *Group) {
		g.Id(def.Name + "TypeNONE").Op("=").Lit(0)
		for i, field := range def.Fields {
			g.Id(def.Name + "Type" + toExportedName(field.Name)).Op("=").Lit(i + 1)
		}
	})
	f.Line()
}
